### ISSUE TITLE
(Bug report) Update Trilium wiki/repo links to reference TriliumNext wiki/repo

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Notes#270]
### Description

All references to the zadam/trilium repo/wiki need to be updated to use the TriliumNext repo/wiki

**Comment by eliandoran** [comment]
@meichthys , we could do that, but I'm not sure if the current format of the Wiki is suitable for our needs.

Take for example https://github.com/zadam/trilium/wiki/Sharing. Our wiki is instead a repository with markdown files, so it has to be linking to https://github.com/TriliumNext/Docs/blob/main/Wiki/sharing.md. Due to this, we are lacking the navigation functionality of the previous wiki.

Why didn't we just copy the Wiki functionality in the same manner as the original?

cc. @Alumniminium

**Comment by Alumniminium** [comment]
We are in fact copying the wiki functionality. Afaik you can turn a repo into a wiki on github. We're just missing a TOC for the sidebar, @root-hal9000 is working on that.

**Comment by eliandoran** [comment]
Done in https://github.com/TriliumNext/Notes/commit/85eaf0cb52e02627f53dff93a54ded98a617dbee and https://github.com/TriliumNext/Notes/commit/c3b742df3bef9d19cdee298a20f1b24036894661.
