### ISSUE TITLE
Docker reporting container as not healthy

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#296]
Could be that the healthcheck script is broken. To investigate.

**Comment by dariuszszyc** [comment]
Same on my side, even though the logs don't mention any issues - only a successful migration. 
However I cannot see any Web UI and the desktop app cannot connect to the Server.

**Comment by hulmgulm** [comment]
That's the output form the health check:
`file:///usr/src/app/docker_healthcheck.js:1 const http = require("http"); ^ ReferenceError: require is not defined in ES module scope, you can use import instead This file is being treated as an ES module because it has a '.js' file extension and '/usr/src/app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension. at file:///usr/src/app/docker_healthcheck.js:1:14 at ModuleJob.run (node:internal/modules/esm/module_job:222:25) at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) Node.js v20.15.1`

**Comment by eliandoran** [comment]
> Same on my side, even though the logs don't mention any issues - only a successful migration. However I cannot see any Web UI and the desktop app cannot connect to the Server.

This sounds like a serious issue. Could you please try to take logs? Try restarting the container to have as much information as possible.

**Comment by foux** [comment]
Same issue on me, making it unavailable on Traefik

**Comment by eliandoran** [comment]
> Same issue on me, making it unavailable on Traefik

@foux , is the container marked unhealthy, but is it working normally for you?
Or are you having the same issue as @dariuszszyc who is unable to access the Trilium instance?

**Comment by foux** [comment]
The container is marked as unhealthy. If I expose the port, I can access Trillium on myhost:port. But the Traefik proxy doesn't work, because Traefik doesn't create proxy for unhealthy containers.

So my issue is really only the unhealthy container. Traefik not creatink the proxy is directly because of this.

**Comment by eliandoran** [comment]
@foux , thank you for the clarification. In this case, I'll prioritize fixing the healthcheck.
I should have a fix available by the end of the day.

**Comment by dariuszszyc** [comment]
My case is also with Traefik, sorry for not mentioning this earlier.

**Comment by eliandoran** [comment]
@foux , @dariuszszyc ,

The issue should be solved now, please have a look at https://hub.docker.com/layers/triliumnext/notes/develop/images/sha256-2a88629322894d86e73011b454820ca2a04cb31bd00654855aa659f67a94cb69?context=explore and let me know if it works out for you.

I have taken the time to add a build step in the CI to check if the healthcheck passes to make sure we don't run into it again.

I will not deploy a new version yet with just this change, but expect a new release in a couple of days.

**Comment by dariuszszyc** [comment]
@eliandoran it did fix the issue for me.
I can now access the Web version and the Desktop also can now sync with server.

**Comment by eliandoran** [comment]
@dariuszszyc , thank you for the very prompt response.

**Comment by foux** [comment]
Sorry for the late reply it's OK for me too, thanks!

**Comment by eliandoran** [comment]
@foux , that was me trying to fix multiplatform builds. It's not finished yet and we should develop soon on all previously compatible platforms.
