### ISSUE TITLE
(Bug report) mindmap: (other) conflicting shortcuts with the rest of the app

### ISSUE THREAD

**Issue by rom1dep** [TriliumNext/Notes#387]
### TriliumNext Version

git-c2ce7d617aff

### What operating system are you using?

Other (specify below)

### What is your setup?

Local (no sync)

### Operating System Version

N/A

### Description

This is a follow-up of #385 
Other conflicting shortcuts include:

- [x] F1: Center mind map
- [ ] Ctrl + "+" Zoom in mind map
- [ ] Ctrl + "-" Zoom out mind map
- [ ] Ctrl + 0 Reset size

**Comment by eliandoran** [comment]
@rom1dep , can you confirm that <kbd>Ctrl</kbd> + <kbd>+</kbd>, <kbd>Ctrl</kbd>+ <kbd>-</kbd> and <kbd>Ctrl</kbd>+ <kbd>0</kbd> are caused by Trilium interfering with its global shortcuts?

On Firefox these combinations don't work at all, on Electron I can use them just fine without any changes (as long as the mind map has focus of course).

The only one I can reproduce from your list is the <kbd>F1</kbd>, for which I have a fix.

**Comment by rom1dep** [comment]
> can you confirm that Ctrl + +, Ctrl+ - and Ctrl+ 0 are caused by Trilium interfering with its global shortcuts?

@eliandoran can confirm this behaviour in Electron (can't try firefox ATM), across all my installed themes. This causes the whole UI to zoom in and out, not just the mind map (even when it is in focus, e.g. when renaming a node).

**Comment by eliandoran** [comment]
@rom1dep , what OS? I tried on Windows on my side.

**Comment by rom1dep** [comment]
This was on Linux
