### ISSUE TITLE
There are horizontal lines under all hyperlinks

### ISSUE THREAD

**Issue by zsgcgrs** [TriliumNext/Notes#485]
### TriliumNext Version

0.90.7

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

docker

### Description

There are horizontal lines under all hyperlinks, which are not in the original version. This is very annoying.

**Comment by eliandoran** [comment]
@zsgcgrs , thanks for noticing. It's caused by our recent update to the latest version of Bootstrap, let me know if you find any other discrepancies when compared to an older version.

However I do find it curious that you find the underline very annoying, it's a quite common approach to highlight links. 🤔
