### ISSUE TITLE
(Feature request) choose CKEditor's editor type

### ISSUE THREAD

**Issue by chncho** [TriliumNext/Notes#539]
### Describe feature

It is highly anticipated to allow the configuration of CKEditor's editor type (such as the classic editor type, which will improve editing efficiency, whether for computer or mobile devices), which can be made into configuration items. Configuration items can be placed in the config file or in the software's "options".

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

**Comment by eliandoran** [comment]
@chncho , I thought of this as well. Generally it's possible but currently the work effort to do it is too high (it involves setting up CKEditor from scratch, since the layout is determined by the build of CKEditor we are using).

We also have some specific changes to the CKEditor that we would have to add to all the various editors.

**Comment by eliandoran** [comment]
Done in https://github.com/TriliumNext/Notes/pull/571.
