### ISSUE TITLE
Translations for 0.90.12

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#594]
Hello,

As we are reaching a new stable build, translations would be needed in order to have a complete software:

- [x] cn: 92.7% (missing 97), @Nriver 
- [ ] de: 85.2% (missing 197), @j13055
- [x] es: 99.7% (missing 4), @hasecilu
- [ ] fr: 98.3% (missing 23), @Potjoe-97

Thank you.

**Comment by riegera2412** [comment]
Hey,

not sure if this is the right place to offer help. I am German and could help translate. However, I am not sure how that would work, especially since I am not very familiar with github and the workflow.

Anyways, if @eliandoran or @j13055 need help, please feel free to ask. This might speed up the completion of the translation.

Regards,
André

**Comment by Nriver** [comment]
cn updated #673

**Comment by j13055** [comment]
Hi, @riegera2412 

i added you to my fork. There we can improve the translation for german further more. I finished it up for the 0.90.12 stable release so far, but there is always improvements possibilities, especially for consistency reasons.

**Comment by Potjoe-97** [comment]
Hey @eliandoran ! I dont' understand, since on my part, Crowdin dashboard gives me a 100% completion for the french translation. I have to double check

**Comment by eliandoran** [comment]
@Potjoe-97 , most likely the .po file was from an older `develop`. I see you already updated the develop branch on your side so you should be all set. Let me know if you need any help.

**Comment by eliandoran** [comment]
Closing for now; here's the progress for now:

![image](https://github.com/user-attachments/assets/01e82e78-ff53-4b3d-879a-86aff9d5f7fc)
